version: "3"
services:
  webdocs:
    build: .
    ports:
      - "8008:8008"
    volumes:
      - ".:/app"
    container_name: webdocs
    image: webdocs:latest
    command: "uvicorn main:app --host 0.0.0.0 --port webdocs"
